
{{- if not (empty .Values.exchangedServiceAccounts) }}
{{- range .Values.exchangedServiceAccounts }}
{{- if or (not .name) (not .namespace) (empty .annotations) }}
{{- fail "\n\n******************************************************************************\nERROR: STOPPED to prevent incorrect installation!\nEach entry in .Values.exchangedServiceAccounts must have 'name', 'namespace', and non-empty 'annotations'. \nOne or more required values are missing.\n******************************************************************************\n" }}
{{- else }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .name | quote }}
  namespace: {{ .namespace | quote }}
  annotations:
{{ toYaml .annotations | indent 4 }}
{{- end }}
{{- end }}
{{- end }}
