{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "jfrog-registry-operator.serviceAccountName" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
  {{- if not (empty .Values.serviceAccount.annotations) }}
  annotations: 
    {{- include "common.tplvalues.render" (dict "value" .Values.serviceAccount.annotations "context" $) | nindent 4}}
  {{- end }}
{{- end }}
