apiVersion: v1
stringData:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIG1TCCBL2gAwIBAgIQbFWr29AHksedBwzYEZ7WvzANBgkqhkiG9w0BAQwFADCB
    iDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCk5ldyBKZXJzZXkxFDASBgNVBAcTC0pl
    cnNleSBDaXR5MR4wHAYDVQQKExVUaGUgVVNFUlRSVVNUIE5ldHdvcmsxLjAsBgNV
    BAMTJVVTRVJUcnVzdCBSU0EgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkwHhcNMjAw
    MTMwMDAwMDAwWhcNMzAwMTI5MjM1OTU5WjBLMQswCQYDVQQGEwJBVDEQMA4GA1UE
    ChMHWmVyb1NTTDEqMCgGA1UEAxMhWmVyb1NTTCBSU0EgRG9tYWluIFNlY3VyZSBT
    aXRlIENBMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAhmlzfqO1Mdgj
    4W3dpBPTVBX1AuvcAyG1fl0dUnw/MeueCWzRWTheZ35LVo91kLI3DDVaZKW+TBAs
    JBjEbYmMwcWSTWYCg5334SF0+ctDAsFxsX+rTDh9kSrG/4mp6OShubLaEIUJiZo4
    t873TuSd0Wj5DWt3DtpAG8T35l/v+xrN8ub8PSSoX5Vkgw+jWf4KQtNvUFLDq8mF
    WhUnPL6jHAADXpvs4lTNYwOtx9yQtbpxwSt7QJY1+ICrmRJB6BuKRt/jfDJF9Jsc
    RQVlHIxQdKAJl7oaVnXgDkqtk2qddd3kCDXd74gv813G91z7CjsGyJ93oJIlNS3U
    gFbD6V54JMgZ3rSmotYbz98oZxX7MKbtCm1aJ/q+hTv2YK1yMxrnfcieKmOYBbFD
    hnW5O6RMA703dBK92j6XRN2EttLkQuujZgy+jXRKtaWMIlkNkWJmOiHmErQngHvt
    iNkIcjJumq1ddFX4iaTI40a6zgvIBtxFeDs2RfcaH73er7ctNUUqgQT5rFgJhMmF
    x76rQgB5OZUkodb5k2ex7P+Gu4J86bS15094UuYcV09hVeknmTh5Ex9CBKipLS2W
    2wKBakf+aVYnNCU6S0nASqt2xrZpGC1v7v6DhuepyyJtn3qSV2PoBiU5Sql+aARp
    wUibQMGm44gjyNDqDlVp+ShLQlUH9x8CAwEAAaOCAXUwggFxMB8GA1UdIwQYMBaA
    FFN5v1qqK0rPVIDh2JvAnfKyA2bLMB0GA1UdDgQWBBTI2XhootkZaNU9ct5fCj7c
    tYaGpjAOBgNVHQ8BAf8EBAMCAYYwEgYDVR0TAQH/BAgwBgEB/wIBADAdBgNVHSUE
    FjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwIgYDVR0gBBswGTANBgsrBgEEAbIxAQIC
    TjAIBgZngQwBAgEwUAYDVR0fBEkwRzBFoEOgQYY/aHR0cDovL2NybC51c2VydHJ1
    c3QuY29tL1VTRVJUcnVzdFJTQUNlcnRpZmljYXRpb25BdXRob3JpdHkuY3JsMHYG
    CCsGAQUFBwEBBGowaDA/BggrBgEFBQcwAoYzaHR0cDovL2NydC51c2VydHJ1c3Qu
    Y29tL1VTRVJUcnVzdFJTQUFkZFRydXN0Q0EuY3J0MCUGCCsGAQUFBzABhhlodHRw
    Oi8vb2NzcC51c2VydHJ1c3QuY29tMA0GCSqGSIb3DQEBDAUAA4ICAQAVDwoIzQDV
    ercT0eYqZjBNJ8VNWwVFlQOtZERqn5iWnEVaLZZdzxlbvz2Fx0ExUNuUEgYkIVM4
    YocKkCQ7hO5noicoq/DrEYH5IuNcuW1I8JJZ9DLuB1fYvIHlZ2JG46iNbVKA3ygA
    Ez86RvDQlt2C494qqPVItRjrz9YlJEGT0DrttyApq0YLFDzf+Z1pkMhh7c+7fXeJ
    qmIhfJpduKc8HEQkYQQShen426S3H0JrIAbKcBCiyYFuOhfyvuwVCFDfFvrjADjd
    4jX1uQXd161IyFRbm89s2Oj5oU1wDYz5sx+hoCuh6lSs+/uPuWomIq3y1GDFNafW
    +LsHBU16lQo5Q2yh25laQsKRgyPmMpHJ98edm6y2sHUabASmRHxvGiuwwE25aDU0
    2SAeepyImJ2CzB80YG7WxlynHqNhpE7xfC7PzQlLgmfEHdU+tHFeQazRQnrFkW2W
    kqRGIq7cKRnyypvjPMkjeiV9lRdAM9fSJvsB3svUuu1coIG1xxI1yegoGM4r5QP4
    RGIVvYaiI76C0djoSbQ/dkIUUXQuB8AL5jyH34g3BZaaXyvpmnV4ilppMXVAnAYG
    ON51WhJ6W0xNdNJwzYASZYH+tmCWI+N60Gv2NNMGHwMZ7e9bXgzUCZH5FaBFDGR5
    S9VWqHB73Q+OyIVvIbKYcSc2w/aSuFKGSA==
    -----END CERTIFICATE-----

  # cert.pem: |
  #   -----BEGIN CERTIFICATE-----
  #   MIIErDCCA5SgAwIBAgIBATANBgkqhkiG9w0BAQsFADB/MQswCQYDVQQGEwJVUzEL
  #   MAkGA1UECAwCQ0ExFjAUBgNVBAcMDVNhbiBGcmFuY2lzY28xDjAMBgNVBAoMBUpG
  #   cm9nMRwwGgYDVQQDDBN3d3cudGVzdGluZ2FwcC5zaG9wMR0wGwYJKoZIhvcNAQkB
  #   Fg50ZXN0QGpmcm9nLmNvbTAeFw0yNDA3MTMxNjM1MzZaFw0zNDA1MjIxNjM1MzZa
  #   MH8xCzAJBgNVBAYTAlVTMQswCQYDVQQIDAJDQTEWMBQGA1UEBwwNU2FuIEZyYW5j
  #   aXNjbzEOMAwGA1UECgwFSkZyb2cxHDAaBgNVBAMME3d3dy50ZXN0aW5nYXBwLnNo
  #   b3AxHTAbBgkqhkiG9w0BCQEWDnRlc3RAamZyb2cuY29tMIIBIjANBgkqhkiG9w0B
  #   AQEFAAOCAQ8AMIIBCgKCAQEAy9q73LT0iYMK/Ql5+78wIzqveO7WdMyuHq37RSaw
  #   +/3Ry8dDu8hne1sYE7hFVv4jAyxQ/E/J4Web+jYpkCZ4qSqRcP6rLZoi7VsLxWJY
  #   1TPUjz9k4QKylRTW3BpRL1pHUSnWcSizfKPGi7kppYMDiIhbZ9KCaJrmh4eM8xEM
  #   YE1C6rHOyo4Sd+2Tla9KNEYzjUv/Zm9XghksynCNyJ5UOl9xFNAwgxR3eg7eBzWD
  #   SmiJ9CVK60LamufsMq5CYW32rP+d6CmOUg6I9Cw1wczzmWYES5zvGtdeYqw64CO4
  #   wFD5wUf2eSFfV2P7cZpmAO3YLHNCE+jOcYLN2lhkLDK6tQIDAQABo4IBMTCCAS0w
  #   HwYDVR0jBBgwFoAURnoAr4T1i8IaqKv+1jSjXamGoccwCQYDVR0TBAIwADALBgNV
  #   HQ8EBAMCBPAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMIGzBgNVHREE
  #   gaswgaiCSGFlN2Y1MjNlZmRkMzM0OGY1YmFiNjZiMGQyODExNWE3LTEwMjQ5NDI1
  #   MzEuYXAtc291dGgtMS5lbGIuYW1hem9uYXdzLmNvbYITd3d3LnRlc3RpbmdhcHAu
  #   c2hvcIJHYTE0YjUxNGVjODdjMDRjZDU5MTU4Mzg5ZjFkZTU0NjgtNjYzNTIwODYz
  #   LmFwLXNvdXRoLTEuZWxiLmFtYXpvbmF3cy5jb20wHQYDVR0OBBYEFH8i08HD49kv
  #   6AszYAV9Q1ABxmW8MA0GCSqGSIb3DQEBCwUAA4IBAQAkem8t55pDLGxg7bmj36f/
  #   K4DEhBcVD8bZTLGxF1UQt9GRxh2YdOcmx+kVFgE43r51NhWzxlSKw/KpG2pQjkTP
  #   gmry62+O2EmM6P5RXiRdjLKlHhzHV2bM4IE6Z8396OH7I5YT35B+0JV+Xnby5QVi
  #   ei68aZfpSwOeNsbUcc57izRsSXo6Emz5Rz19jFJj/7avtxVUofFxthwCyAWnLtkk
  #   Ep64c7A1oz+w8G8BjpHOJsSd1ZLUxJ/YmexWVmUxVxXjCTArbTI+h9CJq3R29a0o
  #   7lcBBPwNpaY5YN9W323t4Axu3pH3KWSXeALPAUF+OG+B+yss2U9WhuFiAYBH6fbl
  #   -----END CERTIFICATE-----

kind: Secret
metadata:
  name: certs
  namespace: testing
type: Opaque
