---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resourceNames:
  - jfrog-operator-sa
  resources:
  - serviceaccounts
  verbs:
  - get
- apiGroups:
  - ""
  resourceNames:
  - jfrog-operator-sa
  resources:
  - serviceaccounts/token
  verbs:
  - create
  - get
- apiGroups:
  - ""
  - apps
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  - apps
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - ""
  - apps
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.jfrog.com
  resources:
  - secretrotators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.jfrog.com
  resources:
  - secretrotators/finalizers
  verbs:
  - update
- apiGroups:
  - apps.jfrog.com
  resources:
  - secretrotators/status
  verbs:
  - get
  - patch
  - update
