apiVersion: apps.jfrog.com/v1alpha1
kind: SecretRotator
metadata:
  labels:
    app.kubernetes.io/name: secretrotators.apps.jfrog.com
    app.kubernetes.io/instance: secretrotator-sample
    app.kubernetes.io/created-by: artifactory-secrets-rotator
  name: secretrotator-sample2
  namespace: jfrog-operator
spec:
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: jfrog-operator
  generatedSecrets:
  - secretName: token-imagepull-secret
    secretType: docker
  # - secretName: token-generic-secret
  #   secretType: generic
  artifactoryUrl: ""
  refreshTime: 10m
  secretMetadata:
    annotations:
      annotationKey: annotationValue
    labels:
      labelName: labelValue
  security:
    enabled: false
    secretNamespace:
    ## Secret can have cert.pem, key.pem and ca.pem keys
    ## NOTE: You can provide either a pair of cert.pem and key.pem, or ca.pem, or all three: cert.pem, key.pem, and ca.pem. But make sure that key needs to same as cert.pem, key.pem, and ca.pem in secret
    certificateSecretName:
    insecureSkipVerify: false
  # serviceAccount: # The default name and namespace will be the operator’s service account name and namespace
  #   name: ""
  #   namespace: ""