{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "jfrog-registry-operator.serviceAccountName" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
  {{- if not .Values.serviceAccount.annotations }}
  annotations: 
    {{ required "\n\n******************************************************************************\nIMPORTANT: STOPPED to prevent false Installation! \nNote: Make sure to pass the current .Values.serviceAccount.annotations \n\nExample Info: \nexport ANNOTATIONS='eks.amazonaws.com/role-arn: arn:aws:iam::000000000000:role/jfrog-operator-role' \nAdd set in helm install command: --set serviceAccount.annotations=${ANNOTATIONS} \n\n******************************************************************************" .Values.serviceAccount.annotations | quote }}
  {{- else }}
  annotations: 
    {{- include "common.tplvalues.render" (dict "value" .Values.serviceAccount.annotations "context" $) | nindent 4}}
  {{- end }}
{{- end }}
